export const districts = [
  { name: 'Bo', code: 'Bo' },
  { name: 'Bombali', code: 'Bombali' },
  { name: 'Bonthe', code: 'Bonthe' },
  { name: 'Falaba', code: 'Falaba' },
  { name: 'Kailahun', code: 'Kailahun' },
  { name: 'Kambia', code: 'Kambia' },
  { name: 'Karene', code: 'Karene' },
  { name: 'Kenema', code: 'Kenema' },
  { name: 'Koinadugu', code: 'Koinadugu' },
  { name: 'Kono', code: 'Kono' },
  { name: 'Moyamba', code: 'Moyamba' },
  { name: 'Port Loko', code: 'Port Loko' },
  { name: 'Pujehun', code: 'Pujehun' },
  { name: 'Tonkolili', code: 'Tonkolili' },
  { name: 'Western Rural', code: 'Western Rural' },
  { name: 'Western Urban', code: 'Western Urban' },
];
